import {
  LAMPORTS_PER_SOL,
  PublicKey,
  SystemProgram,
  Transaction,
  sendAndConfirmTransaction,
} from "@solana/web3.js";

import { junoJson, junoOptions } from "@/lib/juno/api";
import { cluster } from "@/lib/juno/cluster";
import { getConnection } from "@/lib/juno/dbc";
import { faucetKeypair } from "@/lib/juno/faucet";
import { check } from "@/lib/rate-limit";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const OPTIONS = junoOptions;

/** Enough for a launch (two transactions plus rent) and a few small buys. */
const AMOUNT_SOL = 0.2;

/**
 * Devnet SOL for a new wallet.
 *
 * A wallet created on this device starts empty, and every action in Juno —
 * a buy, a launch — costs a fee. Without a way to fund it, a first-time user
 * could look at everything and do nothing.
 *
 * Juno's own faucet key first (`lib/juno/faucet.ts` — generated by the server,
 * sealed at rest, funded by the operator), because it answers in a second and
 * does not run dry at random. Solana's public faucet second, for when Juno's
 * is empty. With neither, a readable refusal and the public faucet's address,
 * never a fake balance.
 *
 * Devnet only: on any other cluster this refuses before touching the chain.
 */
export async function GET() {
  if (cluster() !== "devnet") {
    return junoJson({ error: "The faucet only runs on devnet." }, { status: 404 });
  }
  try {
    const key = await faucetKeypair();
    const lamports = await getConnection().getBalance(key.publicKey);
    return junoJson({ address: key.publicKey.toBase58(), balance: lamports / LAMPORTS_PER_SOL, amount: AMOUNT_SOL });
  } catch (error) {
    return junoJson(
      { error: error instanceof Error ? error.message : "The faucet is not configured" },
      { status: 503 },
    );
  }
}

export async function POST(request: Request) {
  if (cluster() !== "devnet") {
    return junoJson({ error: "The faucet only runs on devnet." }, { status: 404 });
  }

  let wallet: PublicKey;
  try {
    const body = (await request.json()) as { wallet?: unknown };
    wallet = new PublicKey(typeof body.wallet === "string" ? body.wallet : "");
  } catch {
    return junoJson({ error: "wallet is not an address" }, { status: 400 });
  }

  // Per wallet and per network address, so one visitor cannot drain it by
  // minting fresh wallets in a loop.
  const ip = request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || "unknown";
  for (const [key, limit, windowMs] of [
    [`faucet:${wallet.toBase58()}`, 3, 10 * 60_000],
    [`faucet-ip:${ip}`, 6, 60 * 60_000],
  ] as const) {
    const limited = check(key, limit, windowMs);
    if (!limited.ok) {
      return junoJson(
        {
          error: `Too many faucet requests. Try again in ${Math.ceil(limited.retryAfter / 60)} min.`,
          retryAfter: limited.retryAfter,
        },
        { status: 429 },
      );
    }
  }

  const connection = getConnection();
  const lamports = Math.round(AMOUNT_SOL * LAMPORTS_PER_SOL);

  // Juno's faucet, when it holds enough to pay and keep its own fee.
  const funder = await faucetKeypair().catch(() => null);
  if (funder) {
    const balance = await connection.getBalance(funder.publicKey).catch(() => 0);
    if (balance > lamports + 10_000) {
      try {
        const signature = await sendAndConfirmTransaction(
          connection,
          new Transaction().add(
            SystemProgram.transfer({ fromPubkey: funder.publicKey, toPubkey: wallet, lamports }),
          ),
          [funder],
          { commitment: "confirmed" },
        );
        return junoJson({ signature, amount: AMOUNT_SOL, source: "juno-faucet" });
      } catch {
        // Fall through to the public faucet.
      }
    }
  }

  try {
    const signature = await connection.requestAirdrop(wallet, lamports);
    const latest = await connection.getLatestBlockhash();
    await connection.confirmTransaction({ signature, ...latest }, "confirmed");
    return junoJson({ signature, amount: AMOUNT_SOL, source: "public-faucet" });
  } catch (publicError) {
    return junoJson(
      {
        error:
          "Both faucets are dry right now. Get devnet SOL at faucet.solana.com with your address, then pull to refresh.",
        faucetUrl: "https://faucet.solana.com",
        detail: publicError instanceof Error ? publicError.message : undefined,
      },
      { status: 503 },
    );
  }
}
