import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import Script from "next/script";
import "./globals.css";
import { Providers } from "@/components/Providers";
import { WalletProviders } from "@/components/WalletProviders";
import { AgeGate } from "@/components/AgeGate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const brandSatoshi = localFont({
  src: "./fonts/Satoshi-Bold.woff2",
  variable: "--font-brand-satoshi",
  display: "swap",
  weight: "700",
});

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";
const SITE_DESCRIPTION =
  "Pay-per-tap premium content with invisible app-balance payments.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  // Per-route layouts set `title: "Search"` etc. and inherit this template,
  // producing unique, descriptive document titles ("Search · Norr").
  title: {
    default: "Norr — lift the veil",
    template: "%s · Norr",
  },
  description: SITE_DESCRIPTION,
  applicationName: "Norr",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "Norr",
  },
  formatDetection: { telephone: false },
  manifest: "/manifest.webmanifest",
  icons: {
    apple: "/apple-touch-icon.png",
  },
  // og/twitter images are generated by app/opengraph-image.tsx and wired in
  // automatically; these tags give shared links a title + description.
  openGraph: {
    type: "website",
    siteName: "Norr",
    title: "Norr — lift the veil",
    description: SITE_DESCRIPTION,
    url: SITE_URL,
  },
  twitter: {
    card: "summary_large_image",
    title: "Norr — lift the veil",
    description: SITE_DESCRIPTION,
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover", // handles iPhone notch
  themeColor: "#000000",
};

// Applies the persisted theme before paint (dark default → no class). No FOUC.
const themeScript = `(function(){try{if(localStorage.getItem('veil-theme')==='light'){document.documentElement.classList.add('light')}}catch(e){}})();`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} ${brandSatoshi.variable} h-full antialiased`}
    >
      <body className="bg-bg text-text flex min-h-full flex-col">
        <Script
          id="veil-theme"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: themeScript }}
        />
        <WalletProviders>
          <Providers>{children}</Providers>
        </WalletProviders>
        {/* Renders above everything until confirmed. A self-attestation, not
            age verification — see the component. */}
        <AgeGate />
      </body>
    </html>
  );
}
