import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import Script from "next/script";
import "./globals.css";
import { Providers } from "@/components/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const brandSatoshi = localFont({
  src: "./fonts/Satoshi-Bold.woff2",
  variable: "--font-brand-satoshi",
  display: "swap",
  weight: "700",
});

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";
const SITE_DESCRIPTION =
  "A social app on Solana where publishing a post launches a Meteora Dynamic " +
  "Bonding Curve pool for it.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  // Per-route layouts set `title: "Explore"` etc. and inherit this template,
  // producing unique, descriptive document titles ("Explore · Juno").
  title: {
    default: "Juno — every post is a market",
    template: "%s · Juno",
  },
  description: SITE_DESCRIPTION,
  applicationName: "Juno",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "Juno",
  },
  formatDetection: { telephone: false },
  manifest: "/manifest.webmanifest",
  icons: {
    apple: "/apple-touch-icon.png",
  },
  // og/twitter images are generated by app/opengraph-image.tsx and wired in
  // automatically; these tags give shared links a title + description.
  openGraph: {
    type: "website",
    siteName: "Juno",
    title: "Juno — every post is a market",
    description: SITE_DESCRIPTION,
    url: SITE_URL,
  },
  twitter: {
    card: "summary_large_image",
    title: "Juno — every post is a market",
    description: SITE_DESCRIPTION,
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover", // handles iPhone notch
  themeColor: "#0d0b12", // --j-bg
};

// Applies the persisted theme before paint (dark default → no class). No FOUC.
const themeScript = `(function(){try{if(localStorage.getItem('juno-theme')==='light'){document.documentElement.classList.add('light')}}catch(e){}})();`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} ${brandSatoshi.variable} h-full antialiased`}
    >
      <body className="bg-bg text-text flex min-h-full flex-col">
        <Script
          id="juno-theme"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: themeScript }}
        />
        {/* Wallets are provided by `app/(juno)/layout.tsx`, not here — the
            adapter is only needed inside the Juno route group. */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
